from typing import Literal, Optional

from pydantic import BaseModel, Field


class JargonRequest(BaseModel):
    term: str = Field(
        ...,
        description="The financial or policy jargon term (e.g., 'Moratorium', 'Promoter Margin')",
    )
    language: str = Field(
        "en",
        description="Target ISO language code (e.g., 'en', 'hi', 'mr')",
    )


class JargonResponse(BaseModel):
    explanation: str = Field(
        ...,
        description="Simplified explanation of the term in the target language",
    )


class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message author (e.g. 'user' or 'model')")
    parts: str = Field(..., description="The text content of the message")


class ChatRequest(BaseModel):
    message: str = Field(..., description="The current user question or message")
    history: list[ChatMessage] = Field(default_factory=list, description="Previous conversation history")
    language: str = Field("en", description="Target ISO language code (e.g., 'en', 'hi', 'mr')")


class ChatResponse(BaseModel):
    response: str = Field(..., description="The grounded, localized response generated by the AI advisor")
    suggested_questions: list[str] = Field(
        default_factory=list,
        description="2-3 relevant follow-up question suggestions for the user in the target language",
    )


class IntentRequest(BaseModel):
    transcript: str = Field(..., description="Raw text or transcription from speech-to-text")
    language: str = Field("en", description="ISO language code of transcription (e.g., 'en', 'hi', 'mr')")


class IntentResponse(BaseModel):
    project_category: Literal["Manufacturing", "Service", "Trading"] = Field(
        ..., description="Categorized project type (Manufacturing, Service, or Trading)"
    )
    requested_amount: float = Field(
        ..., ge=0.0, description="Requested loan amount in INR. Defaults to 0.0 if not detected."
    )
    annual_income: float = Field(
        ..., ge=0.0, description="Applicant's household annual income in INR. Defaults to 0.0 if not detected."
    )
    trade: str = Field(..., description="Specific trade name in English (e.g. Tailoring, Dairy, Barber)")
    gender: str = Field(..., description="Gender (e.g. Male, Female, Other). Defaults to Male if unknown.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of extraction between 0.0 and 1.0")


class ApplicantProfile(BaseModel):
    project_category: str
    requested_amount: float
    annual_income: float
    trade: str
    gender: str


class CandidateScheme(BaseModel):
    scheme_name: str
    max_coverage_pct: float
    interest_rate: float
    eligibility_score: float


class ExplainerRequest(BaseModel):
    applicant: ApplicantProfile
    candidate_schemes: list[CandidateScheme]
    language: str = Field("en", description="Target language of the narrative")


class ExplainerResponse(BaseModel):
    top_scheme: str = Field(..., description="Name of the best-matching scheme")
    explanation: str = Field(..., description="A localized justification explaining why this scheme fits the applicant's profile")
    runner_up_note: str = Field(..., description="Brief note on other candidate options or why they ranked lower")


class ExtractedFields(BaseModel):
    name: str = Field(..., description="Name of the applicant printed on the document")
    category: Optional[str] = Field(None, description="Caste category (SC, ST, OBC, General) extracted from Caste Certificate")
    annual_income: Optional[float] = Field(None, description="Annual income in INR extracted from Income Certificate")
    valid_until: Optional[str] = Field(None, description="Expiration date of document in YYYY-MM-DD format (if applicable)")


class OCRResponse(BaseModel):
    doc_type: str = Field(..., description="Type of certificate processed ('caste' or 'income')")
    extracted_fields: ExtractedFields = Field(..., description="Structured fields extracted from certificate")
    income_verified: bool = Field(..., description="True if document type is income and annual income is extracted and <= 500000.00")
    raw_confidence: float = Field(..., description="Average OCR engine extraction confidence (0.0 to 1.0)")

