from typing import Literal

from pydantic import BaseModel, Field


class JargonRequest(BaseModel):
    term: str = Field(
        ...,
        description="The financial or policy jargon term (e.g., 'Moratorium', 'Promoter Margin')",
    )
    language: str = Field(
        "en",
        description="Target ISO language code (e.g., 'en', 'hi', 'mr')",
    )


class JargonResponse(BaseModel):
    explanation: str = Field(
        ...,
        description="Simplified explanation of the term in the target language",
    )


class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message author (e.g. 'user' or 'model')")
    parts: str = Field(..., description="The text content of the message")


class ChatRequest(BaseModel):
    message: str = Field(..., description="The current user question or message")
    history: list[ChatMessage] = Field(default_factory=list, description="Previous conversation history")
    language: str = Field("en", description="Target ISO language code (e.g., 'en', 'hi', 'mr')")


class ChatResponse(BaseModel):
    response: str = Field(..., description="The grounded, localized response generated by the AI advisor")


class IntentRequest(BaseModel):
    transcript: str = Field(..., description="Raw text or transcription from speech-to-text")
    language: str = Field("en", description="ISO language code of transcription (e.g., 'en', 'hi', 'mr')")


class IntentResponse(BaseModel):
    project_category: Literal["Manufacturing", "Service", "Trading"] = Field(
        ..., description="Categorized project type (Manufacturing, Service, or Trading)"
    )
    requested_amount: float = Field(
        ..., ge=0.0, description="Requested loan amount in INR. Defaults to 0.0 if not detected."
    )
    annual_income: float = Field(
        ..., ge=0.0, description="Applicant's household annual income in INR. Defaults to 0.0 if not detected."
    )
    trade: str = Field(..., description="Specific trade name in English (e.g. Tailoring, Dairy, Barber)")
    gender: str = Field(..., description="Gender (e.g. Male, Female, Other). Defaults to Male if unknown.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score of extraction between 0.0 and 1.0")

